name: .NET Core CI/CD

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted          
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Publish Application
      # Sử dụng dotnet publish để đóng gói app vào thư mục tạm của Runner
      run: dotnet publish ./MyApiApp/MyApiApp.csproj -c Release -o ./MyApiApp/publish

    # --- NHÁNH DEVELOP: Deploy lên cổng 5001 (Staging) ---
    - name: Deploy to Staging (Develop)
      if: github.ref == 'refs/heads/develop'
      env:
        RUNNER_TRACK_PROCESSES: false
      run: |
        sudo systemctl restart myapp-staging.service

    # --- NHÁNH MAIN: Deploy lên cổng 5000 (Production) ---
    - name: Deploy to Production (Main)
      if: github.ref == 'refs/heads/main'
      env:
        RUNNER_TRACK_PROCESSES: false
      run: |
        sudo systemctl restart myapp-production.service